### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by CaptainBloodz** [stefan11111/stefan_overlay#1]
Interesting overlay...

Wouldn't it be nice & handy to add in README.md a command line for adding to /etc/portage/repos.conf:

eselect repository add stefan git https://github.com/stefan11111/stefan_overlay.git

**Comment by stefan11111** [comment]
Done
https://github.com/stefan11111/stefan_overlay/commit/294312ccfaa319096d4fd3a7a941e9a1f170c048

**Comment by CaptainBloodz** [comment]
eselect repository add stefan_overlay git https://github.com/stefan11111/stefan_overlay.git

should be more portage compliant.

**Comment by stefan11111** [comment]
Done 
https://github.com/stefan11111/stefan_overlay/commit/17aa2c1f6b07d5ccd5acc6daf6766ec548c1e8c2
